spring.application.name=@project.name@
spring.application.version=@project.version@
server.port=5020

#con eureka client ya no afecta esta configuracion
#spring.cloud.discovery.client.simple.instances.ms-product-core[0].uri=http://localhost:5010
#spring.cloud.discovery.client.simple.instances.ms-product-core[1].uri=http://localhost:5011

eureka.client.service-url.defaultZone=http://localhost:5001/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

config.endpoint.product.core=http://ms-product-core/api/product