spring.application.name=@project.name@
spring.application.version=@project.version@
server.port=5001

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:5001/eureka/